#!/usr/bin/perl -w

use strict;
use warnings;
use lib "$ENV{'HEEDRA_HOME'}/lib" || '/opt/heedra/lib';
use Heedra;
use Heedra::Log;


#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
our $Heedra  = undef;
#
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


#===============================================================================
#
MAIN:
{

  Info('Starting Heedra Blender Consumer');
  &_init;
  TASK: while (my $message = $Heedra->consume)
  {
    if (not defined $message)
    {
      Info('Queue is Empty');
      last TASK;
    }
    my $message_id = $message->header->get_message_id;
    if ($Heedra->execute($message))
    {
      Info("Completed Task for Message #$message_id");
    }
    else
    {
      Error("Can't Execute Message #$message_id");
    }

    # We're going to try and delete either way
    if ($Heedra->delete_message($message))
    {
      Debug("Deleted Message #$message_id");
      next TASK;
    }
    else
    {
      Fatal("Failed to Delete Message #$message_id");
    }
#TODO Fix exit on empty queue (config file)
  }
  exit;

}
#
#===============================================================================

#-------------------------------------------------------------------------------
#
sub _init #()#
{

  Info('Load Configuration File');

  # Load Config File
  Heedra::Log::set_verbose(1);
  $Heedra = new Heedra;
  Fatal('Could Not Load Configuration File') unless defined $Heedra;

  return;
    
}
#
#-------------------------------------------------------------------------------


__END__

=head1 NAME

Heedra::???? - ???? for Heedra Queuing System

=head1 SYNOPSIS

  use Heedra::????;
  ????

=head1 DESCRIPTION


=head2 EXPORT

None by default.


=head1 SEE ALSO

Project GitHub Site:

   https://github.com/trevharmon/Heedra

=head1 AUTHOR

Trev Harmon

=head1 COPYRIGHT AND LICENSE

Copyright 2016 Trev Harmon

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=cut


